[project]
name = "producer-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "ruff>=0.11.10",
    "spotipy>=2.25.1",
    "wikipedia>=1.4.0",
]
